title: 网页第一
author: some wrap
email: yours-email@dodo.com
description: > # this means to ignore newlines until "baseurl:"
  my 第一个 netsite.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
